In [1]:
import numpy as np

In [ ]:
###############      Basics     ###################

In [2]:
a = np.arange(15).reshape(3, 5)

In [3]:
print a

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [4]:
a.shape

(3, 5)

In [5]:
a.ndim

2

In [7]:
a.dtype.name

'int64'

In [8]:
a.itemsize

8

In [9]:
a.size

15

In [10]:
print type(a)

<type 'numpy.ndarray'>


In [12]:
b = np.array([6, 7, 8])

In [13]:
type(b)

numpy.ndarray

In [14]:
###############      Array Creation     ###################

In [15]:
a = np.array([2,3,4])

In [16]:
a

array([2, 3, 4])

In [17]:
a.dtype

dtype('int64')

In [18]:
b = np.array([1.2, 3.5, 5.1])

In [19]:
b.dtype

dtype('float64')

In [22]:
b = np.array([[1.5, 2, 3],[4, 5, 6]])

In [23]:
b

array([[ 1.5,  2. ,  3. ],
       [ 4. ,  5. ,  6. ]])

In [24]:
c = np.array( [ [1,2], [3,4] ], dtype=complex )

In [25]:
c

array([[ 1.+0.j,  2.+0.j],
       [ 3.+0.j,  4.+0.j]])

In [26]:
######  special creation ######

In [27]:
np.zeros( (3,4) )

array([[ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.]])

In [28]:
np.ones( (2,3,4), dtype=np.int16 ) 

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

In [29]:
np.empty((2, 3))

array([[ 1.5,  2. ,  3. ],
       [ 4. ,  5. ,  6. ]])

In [30]:
np.arange(10, 30, 5)

array([10, 15, 20, 25])

In [31]:
np.arange(0, 2, 0.3)

array([ 0. ,  0.3,  0.6,  0.9,  1.2,  1.5,  1.8])

In [32]:
from numpy import pi

In [33]:
np.linspace(0, 2, 9)

array([ 0.  ,  0.25,  0.5 ,  0.75,  1.  ,  1.25,  1.5 ,  1.75,  2.  ])

In [34]:
x = np.linspace( 0, 2*pi, 100 )        # useful to evaluate function at lots of points

In [35]:
x

array([ 0.        ,  0.06346652,  0.12693304,  0.19039955,  0.25386607,
        0.31733259,  0.38079911,  0.44426563,  0.50773215,  0.57119866,
        0.63466518,  0.6981317 ,  0.76159822,  0.82506474,  0.88853126,
        0.95199777,  1.01546429,  1.07893081,  1.14239733,  1.20586385,
        1.26933037,  1.33279688,  1.3962634 ,  1.45972992,  1.52319644,
        1.58666296,  1.65012947,  1.71359599,  1.77706251,  1.84052903,
        1.90399555,  1.96746207,  2.03092858,  2.0943951 ,  2.15786162,
        2.22132814,  2.28479466,  2.34826118,  2.41172769,  2.47519421,
        2.53866073,  2.60212725,  2.66559377,  2.72906028,  2.7925268 ,
        2.85599332,  2.91945984,  2.98292636,  3.04639288,  3.10985939,
        3.17332591,  3.23679243,  3.30025895,  3.36372547,  3.42719199,
        3.4906585 ,  3.55412502,  3.61759154,  3.68105806,  3.74452458,
        3.8079911 ,  3.87145761,  3.93492413,  3.99839065,  4.06185717,
        4.12532369,  4.1887902 ,  4.25225672,  4.31572324,  4.37

In [36]:
###############      Printing Arrays     ###################

In [37]:
a = np.arange(6)                         # 1d array

In [38]:
print a

[0 1 2 3 4 5]


In [39]:
b = np.arange(12).reshape(4, 3)

In [40]:
print b

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [41]:
c = np.arange(24).reshape(2,3,4)

In [42]:
print c

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [43]:
###############      Basic Operations     ###################

In [44]:
a = np.array( [20,30,40,50] )

In [45]:
b = np.arange( 4 )

In [46]:
c = a - b

In [47]:
c

array([20, 29, 38, 47])

In [48]:
b**2

array([0, 1, 4, 9])

In [49]:
10*np.sin(a)

array([ 9.12945251, -9.88031624,  7.4511316 , -2.62374854])

In [50]:
a<35

array([ True,  True, False, False], dtype=bool)